name: TerrenosPlus
version: '1.0.0'
main: com.rpgcustom.terrenosplus.TerrenosPlus
api-version: '26.3'
author: donnie1337
description: Sistema próprio de terrenos com seleção por pá de ouro.
softdepend: [CargoPlus]

commands:
  terreno:
    description: Gerencia seus terrenos.
    usage: /terreno <info|remover|listar|trust <nickname>|untrust <nickname>|explosao|expandir <direcao> <quantidade>>
    aliases: [terrenos]
  marcos:
    description: Abre o menu de Marcos.
    usage: /marcos [testtempo]
    aliases: [marco]

permissions:
  terrenosplus.use:
    description: Permite criar e gerenciar terrenos.
    default: true
  terrenosplus.bypass:
    description: Ignora proteções de terrenos.
    default: false
  terrenosplus.admin:
    description: Permite ações administrativas do TerrenosPlus.
    default: false
